#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi

# nome do computador
HOST=`hostname`

#  executa a aplicação (-OO)
/usr/bin/env python ./adapter.py "$@" 2> ./adapter.$HOST.log
