# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_anv_edit_new.ui'
#
# Created: Wed Jun 28 15:19:33 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgAnvEditNEW(object):
    def setupUi(self, CDlgAnvEditNEW):
        CDlgAnvEditNEW.setObjectName(_fromUtf8("CDlgAnvEditNEW"))
        CDlgAnvEditNEW.setWindowModality(QtCore.Qt.WindowModal)
        CDlgAnvEditNEW.resize(546, 561)
        CDlgAnvEditNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgAnvEditNEW.setSizeGripEnabled(True)
        CDlgAnvEditNEW.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(CDlgAnvEditNEW)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frmIdt = QtGui.QFrame(CDlgAnvEditNEW)
        self.frmIdt.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmIdt.setFrameShadow(QtGui.QFrame.Raised)
        self.frmIdt.setObjectName(_fromUtf8("frmIdt"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frmIdt)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbxIdt = QtGui.QGroupBox(self.frmIdt)
        self.gbxIdt.setObjectName(_fromUtf8("gbxIdt"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbxIdt)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblMatr = QtGui.QLabel(self.gbxIdt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMatr.sizePolicy().hasHeightForWidth())
        self.lblMatr.setSizePolicy(sizePolicy)
        self.lblMatr.setObjectName(_fromUtf8("lblMatr"))
        self.gridLayout_4.addWidget(self.lblMatr, 0, 0, 1, 1)
        self.qleSSR = QtGui.QLineEdit(self.gbxIdt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleSSR.sizePolicy().hasHeightForWidth())
        self.qleSSR.setSizePolicy(sizePolicy)
        self.qleSSR.setMaxLength(4)
        self.qleSSR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleSSR.setObjectName(_fromUtf8("qleSSR"))
        self.gridLayout_4.addWidget(self.qleSSR, 2, 2, 1, 1)
        self.cbxPrf = QtGui.QComboBox(self.gbxIdt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxPrf.sizePolicy().hasHeightForWidth())
        self.cbxPrf.setSizePolicy(sizePolicy)
        self.cbxPrf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxPrf.setMaxVisibleItems(5)
        self.cbxPrf.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cbxPrf.setObjectName(_fromUtf8("cbxPrf"))
        self.gridLayout_4.addWidget(self.cbxPrf, 1, 2, 1, 1)
        self.qleInd = QtGui.QLineEdit(self.gbxIdt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleInd.sizePolicy().hasHeightForWidth())
        self.qleInd.setSizePolicy(sizePolicy)
        self.qleInd.setMaxLength(7)
        self.qleInd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleInd.setObjectName(_fromUtf8("qleInd"))
        self.gridLayout_4.addWidget(self.qleInd, 0, 2, 1, 1)
        self.lblPrf = QtGui.QLabel(self.gbxIdt)
        self.lblPrf.setObjectName(_fromUtf8("lblPrf"))
        self.gridLayout_4.addWidget(self.lblPrf, 1, 0, 1, 1)
        self.lblSSR = QtGui.QLabel(self.gbxIdt)
        self.lblSSR.setObjectName(_fromUtf8("lblSSR"))
        self.gridLayout_4.addWidget(self.lblSSR, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbxIdt)
        self.verticalLayout.addWidget(self.frmIdt)
        self.frmGrp2 = QtGui.QFrame(CDlgAnvEditNEW)
        self.frmGrp2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGrp2.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGrp2.setLineWidth(1)
        self.frmGrp2.setObjectName(_fromUtf8("frmGrp2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmGrp2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gbxOp = QtGui.QGroupBox(self.frmGrp2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbxOp.sizePolicy().hasHeightForWidth())
        self.gbxOp.setSizePolicy(sizePolicy)
        self.gbxOp.setObjectName(_fromUtf8("gbxOp"))
        self.gridLayout = QtGui.QGridLayout(self.gbxOp)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.gbxOp)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.qleAdOri = QtGui.QLineEdit(self.gbxOp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleAdOri.sizePolicy().hasHeightForWidth())
        self.qleAdOri.setSizePolicy(sizePolicy)
        self.qleAdOri.setMaxLength(4)
        self.qleAdOri.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleAdOri.setObjectName(_fromUtf8("qleAdOri"))
        self.gridLayout.addWidget(self.qleAdOri, 0, 2, 1, 1)
        self.qleAdDst = QtGui.QLineEdit(self.gbxOp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleAdDst.sizePolicy().hasHeightForWidth())
        self.qleAdDst.setSizePolicy(sizePolicy)
        self.qleAdDst.setMaxLength(4)
        self.qleAdDst.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleAdDst.setObjectName(_fromUtf8("qleAdDst"))
        self.gridLayout.addWidget(self.qleAdDst, 3, 2, 1, 1)
        self.cbxProc = QtGui.QComboBox(self.gbxOp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxProc.sizePolicy().hasHeightForWidth())
        self.cbxProc.setSizePolicy(sizePolicy)
        self.cbxProc.setObjectName(_fromUtf8("cbxProc"))
        self.gridLayout.addWidget(self.cbxProc, 7, 2, 1, 1)
        self.qsbAtvPndMin = QtGui.QSpinBox(self.gbxOp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbAtvPndMin.sizePolicy().hasHeightForWidth())
        self.qsbAtvPndMin.setSizePolicy(sizePolicy)
        self.qsbAtvPndMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbAtvPndMin.setSuffix(_fromUtf8(""))
        self.qsbAtvPndMin.setMaximum(1440)
        self.qsbAtvPndMin.setObjectName(_fromUtf8("qsbAtvPndMin"))
        self.gridLayout.addWidget(self.qsbAtvPndMin, 9, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.gbxOp)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lblProc = QtGui.QLabel(self.gbxOp)
        self.lblProc.setObjectName(_fromUtf8("lblProc"))
        self.gridLayout.addWidget(self.lblProc, 7, 0, 1, 1)
        self.label = QtGui.QLabel(self.gbxOp)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.gbxOp)
        self.verticalLayout.addWidget(self.frmGrp2)
        self.frmGrp1 = QtGui.QFrame(CDlgAnvEditNEW)
        self.frmGrp1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGrp1.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGrp1.setLineWidth(1)
        self.frmGrp1.setObjectName(_fromUtf8("frmGrp1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmGrp1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gbxPos = QtGui.QGroupBox(self.frmGrp1)
        self.gbxPos.setMinimumSize(QtCore.QSize(150, 0))
        self.gbxPos.setObjectName(_fromUtf8("gbxPos"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.gbxPos)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.widPos = QtGui.QWidget(self.gbxPos)
        self.widPos.setObjectName(_fromUtf8("widPos"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widPos)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblPosX = QtGui.QLabel(self.widPos)
        self.lblPosX.setObjectName(_fromUtf8("lblPosX"))
        self.gridLayout_5.addWidget(self.lblPosX, 0, 0, 1, 1)
        self.lblPosY = QtGui.QLabel(self.widPos)
        self.lblPosY.setObjectName(_fromUtf8("lblPosY"))
        self.gridLayout_5.addWidget(self.lblPosY, 1, 0, 1, 1)
        self.qsbPosX = QtGui.QDoubleSpinBox(self.widPos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbPosX.sizePolicy().hasHeightForWidth())
        self.qsbPosX.setSizePolicy(sizePolicy)
        self.qsbPosX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbPosX.setDecimals(4)
        self.qsbPosX.setMinimum(-90.0)
        self.qsbPosX.setMaximum(90.0)
        self.qsbPosX.setObjectName(_fromUtf8("qsbPosX"))
        self.gridLayout_5.addWidget(self.qsbPosX, 0, 1, 1, 1)
        self.qsbPosY = QtGui.QDoubleSpinBox(self.widPos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbPosY.sizePolicy().hasHeightForWidth())
        self.qsbPosY.setSizePolicy(sizePolicy)
        self.qsbPosY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbPosY.setDecimals(4)
        self.qsbPosY.setMinimum(-180.0)
        self.qsbPosY.setMaximum(180.0)
        self.qsbPosY.setObjectName(_fromUtf8("qsbPosY"))
        self.gridLayout_5.addWidget(self.qsbPosY, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.widPos)
        self.horizontalLayout_2.addWidget(self.gbxPos)
        self.gbxNav = QtGui.QGroupBox(self.frmGrp1)
        self.gbxNav.setObjectName(_fromUtf8("gbxNav"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbxNav)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widNavPro = QtGui.QWidget(self.gbxNav)
        self.widNavPro.setObjectName(_fromUtf8("widNavPro"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widNavPro)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.qsbNavPro = QtGui.QDoubleSpinBox(self.widNavPro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbNavPro.sizePolicy().hasHeightForWidth())
        self.qsbNavPro.setSizePolicy(sizePolicy)
        self.qsbNavPro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbNavPro.setSuffix(_fromUtf8(""))
        self.qsbNavPro.setDecimals(1)
        self.qsbNavPro.setMaximum(360.0)
        self.qsbNavPro.setSingleStep(5.0)
        self.qsbNavPro.setObjectName(_fromUtf8("qsbNavPro"))
        self.horizontalLayout_9.addWidget(self.qsbNavPro)
        self.gridLayout_2.addWidget(self.widNavPro, 0, 1, 1, 1)
        self.lblNavAlt = QtGui.QLabel(self.gbxNav)
        self.lblNavAlt.setObjectName(_fromUtf8("lblNavAlt"))
        self.gridLayout_2.addWidget(self.lblNavAlt, 1, 0, 1, 1)
        self.lblNavPro = QtGui.QLabel(self.gbxNav)
        self.lblNavPro.setObjectName(_fromUtf8("lblNavPro"))
        self.gridLayout_2.addWidget(self.lblNavPro, 0, 0, 1, 1)
        self.lblNavVel = QtGui.QLabel(self.gbxNav)
        self.lblNavVel.setObjectName(_fromUtf8("lblNavVel"))
        self.gridLayout_2.addWidget(self.lblNavVel, 2, 0, 1, 1)
        self.qsbNavVel = QtGui.QDoubleSpinBox(self.gbxNav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbNavVel.sizePolicy().hasHeightForWidth())
        self.qsbNavVel.setSizePolicy(sizePolicy)
        self.qsbNavVel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbNavVel.setSuffix(_fromUtf8(""))
        self.qsbNavVel.setDecimals(1)
        self.qsbNavVel.setMaximum(1000.0)
        self.qsbNavVel.setSingleStep(10.0)
        self.qsbNavVel.setObjectName(_fromUtf8("qsbNavVel"))
        self.gridLayout_2.addWidget(self.qsbNavVel, 2, 1, 1, 1)
        self.qsbNavAlt = QtGui.QDoubleSpinBox(self.gbxNav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbNavAlt.sizePolicy().hasHeightForWidth())
        self.qsbNavAlt.setSizePolicy(sizePolicy)
        self.qsbNavAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbNavAlt.setSuffix(_fromUtf8(""))
        self.qsbNavAlt.setDecimals(1)
        self.qsbNavAlt.setMaximum(99900.0)
        self.qsbNavAlt.setSingleStep(50.0)
        self.qsbNavAlt.setObjectName(_fromUtf8("qsbNavAlt"))
        self.gridLayout_2.addWidget(self.qsbNavAlt, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbxNav)
        self.verticalLayout.addWidget(self.frmGrp1)
        self.bbxAnvEdit = QtGui.QWidget(CDlgAnvEditNEW)
        self.bbxAnvEdit.setObjectName(_fromUtf8("bbxAnvEdit"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.bbxAnvEdit)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnCancel = QtGui.QPushButton(self.bbxAnvEdit)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_6.addWidget(self.btnCancel)
        self.btnOk = QtGui.QPushButton(self.bbxAnvEdit)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/editedit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon1)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout_6.addWidget(self.btnOk)
        self.verticalLayout.addWidget(self.bbxAnvEdit)
        self.lblMatr.setBuddy(self.qleInd)
        self.lblNavAlt.setBuddy(self.qsbNavAlt)
        self.lblNavPro.setBuddy(self.qsbNavPro)
        self.lblNavVel.setBuddy(self.qsbNavVel)

        self.retranslateUi(CDlgAnvEditNEW)
        QtCore.QMetaObject.connectSlotsByName(CDlgAnvEditNEW)
        CDlgAnvEditNEW.setTabOrder(self.qleInd, self.cbxPrf)
        CDlgAnvEditNEW.setTabOrder(self.cbxPrf, self.qleSSR)
        CDlgAnvEditNEW.setTabOrder(self.qleSSR, self.qleAdOri)
        CDlgAnvEditNEW.setTabOrder(self.qleAdOri, self.qleAdDst)
        CDlgAnvEditNEW.setTabOrder(self.qleAdDst, self.cbxProc)
        CDlgAnvEditNEW.setTabOrder(self.cbxProc, self.qsbAtvPndMin)
        CDlgAnvEditNEW.setTabOrder(self.qsbAtvPndMin, self.qsbPosX)
        CDlgAnvEditNEW.setTabOrder(self.qsbPosX, self.qsbPosY)
        CDlgAnvEditNEW.setTabOrder(self.qsbPosY, self.qsbNavPro)
        CDlgAnvEditNEW.setTabOrder(self.qsbNavPro, self.qsbNavAlt)
        CDlgAnvEditNEW.setTabOrder(self.qsbNavAlt, self.qsbNavVel)
        CDlgAnvEditNEW.setTabOrder(self.qsbNavVel, self.btnCancel)
        CDlgAnvEditNEW.setTabOrder(self.btnCancel, self.btnOk)

    def retranslateUi(self, CDlgAnvEditNEW):
        CDlgAnvEditNEW.setWindowTitle(_translate("CDlgAnvEditNEW", "Edição de Aeronaves", None))
        self.gbxIdt.setTitle(_translate("CDlgAnvEditNEW", "Identificação", None))
        self.lblMatr.setText(_translate("CDlgAnvEditNEW", "<html><head/><body><p>Indicativo:</p></body></html>", None))
        self.lblPrf.setText(_translate("CDlgAnvEditNEW", "<html><head/><body><p>Tipo da Aeronave:</p></body></html>", None))
        self.lblSSR.setText(_translate("CDlgAnvEditNEW", "<html><head/><body><p>SSR:</p></body></html>", None))
        self.gbxOp.setTitle(_translate("CDlgAnvEditNEW", "Informações Operacionais", None))
        self.label_3.setText(_translate("CDlgAnvEditNEW", "Tempo de ativação (minutos):", None))
        self.label_2.setText(_translate("CDlgAnvEditNEW", "Aérodromo de Destino:", None))
        self.lblProc.setText(_translate("CDlgAnvEditNEW", "Procedimento:", None))
        self.label.setText(_translate("CDlgAnvEditNEW", "Aeródromo de Origem:", None))
        self.gbxPos.setTitle(_translate("CDlgAnvEditNEW", "Posição", None))
        self.lblPosX.setText(_translate("CDlgAnvEditNEW", "Latitude:", None))
        self.lblPosY.setText(_translate("CDlgAnvEditNEW", "Longitude:", None))
        self.gbxNav.setTitle(_translate("CDlgAnvEditNEW", "Navegação", None))
        self.lblNavAlt.setText(_translate("CDlgAnvEditNEW", "Altitude (ft):", None))
        self.lblNavPro.setText(_translate("CDlgAnvEditNEW", "Proa:", None))
        self.lblNavVel.setText(_translate("CDlgAnvEditNEW", "Velocidade (kt):", None))
        self.btnCancel.setText(_translate("CDlgAnvEditNEW", "Cancela", None))
        self.btnOk.setText(_translate("CDlgAnvEditNEW", "Ok", None))

import resources_rc
