# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_exe_data_new.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgExeDataNEW(object):
    def setupUi(self, CDlgExeDataNEW):
        CDlgExeDataNEW.setObjectName(_fromUtf8("CDlgExeDataNEW"))
        CDlgExeDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        CDlgExeDataNEW.resize(763, 560)
        CDlgExeDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgExeDataNEW.setSizeGripEnabled(True)
        CDlgExeDataNEW.setModal(True)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(CDlgExeDataNEW)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.wid_qwt = QtGui.QWidget(CDlgExeDataNEW)
        self.wid_qwt.setObjectName(_fromUtf8("wid_qwt"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wid_qwt)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.qtw_exe = QtGui.QTableWidget(self.wid_qwt)
        self.qtw_exe.setObjectName(_fromUtf8("qtw_exe"))
        self.qtw_exe.setColumnCount(0)
        self.qtw_exe.setRowCount(0)
        self.verticalLayout_2.addWidget(self.qtw_exe)
        self.horizontalLayout_2.addWidget(self.wid_qwt)
        self.splitter = QtGui.QSplitter(CDlgExeDataNEW)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.wid_data = QtGui.QWidget(self.splitter)
        self.wid_data.setObjectName(_fromUtf8("wid_data"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wid_data)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frm_id = QtGui.QFrame(self.wid_data)
        self.frm_id.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_id.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_id.setLineWidth(1)
        self.frm_id.setObjectName(_fromUtf8("frm_id"))
        self.gridLayout = QtGui.QGridLayout(self.frm_id)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_desc = QtGui.QLabel(self.frm_id)
        self.lbl_desc.setObjectName(_fromUtf8("lbl_desc"))
        self.gridLayout.addWidget(self.lbl_desc, 1, 0, 1, 1)
        self.txt_indc = QtGui.QLabel(self.frm_id)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_indc.setFont(font)
        self.txt_indc.setObjectName(_fromUtf8("txt_indc"))
        self.gridLayout.addWidget(self.txt_indc, 0, 2, 1, 1)
        self.lbl_indc = QtGui.QLabel(self.frm_id)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_indc.sizePolicy().hasHeightForWidth())
        self.lbl_indc.setSizePolicy(sizePolicy)
        self.lbl_indc.setObjectName(_fromUtf8("lbl_indc"))
        self.gridLayout.addWidget(self.lbl_indc, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.qle_desc = QtGui.QLineEdit(self.frm_id)
        self.qle_desc.setObjectName(_fromUtf8("qle_desc"))
        self.gridLayout.addWidget(self.qle_desc, 1, 2, 1, 2)
        self.verticalLayout.addWidget(self.frm_id)
        self.tab_exe = QtGui.QTabWidget(self.wid_data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_exe.sizePolicy().hasHeightForWidth())
        self.tab_exe.setSizePolicy(sizePolicy)
        self.tab_exe.setObjectName(_fromUtf8("tab_exe"))
        self.pag_exe = QtGui.QWidget()
        self.pag_exe.setObjectName(_fromUtf8("pag_exe"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pag_exe)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dsb_exe_vel = QtGui.QDoubleSpinBox(self.pag_exe)
        self.dsb_exe_vel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_exe_vel.setDecimals(1)
        self.dsb_exe_vel.setMinimum(0.1)
        self.dsb_exe_vel.setMaximum(5.0)
        self.dsb_exe_vel.setSingleStep(0.5)
        self.dsb_exe_vel.setProperty("value", 1.0)
        self.dsb_exe_vel.setObjectName(_fromUtf8("dsb_exe_vel"))
        self.gridLayout_2.addWidget(self.dsb_exe_vel, 2, 1, 1, 1)
        self.lbl_vel_exe = QtGui.QLabel(self.pag_exe)
        self.lbl_vel_exe.setObjectName(_fromUtf8("lbl_vel_exe"))
        self.gridLayout_2.addWidget(self.lbl_vel_exe, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.lbl_hor_ini = QtGui.QLabel(self.pag_exe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_hor_ini.sizePolicy().hasHeightForWidth())
        self.lbl_hor_ini.setSizePolicy(sizePolicy)
        self.lbl_hor_ini.setObjectName(_fromUtf8("lbl_hor_ini"))
        self.gridLayout_2.addWidget(self.lbl_hor_ini, 0, 0, 1, 1)
        self.ted_hor_ini = QtGui.QTimeEdit(self.pag_exe)
        self.ted_hor_ini.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ted_hor_ini.setTime(QtCore.QTime(0, 0, 0))
        self.ted_hor_ini.setTimeSpec(QtCore.Qt.LocalTime)
        self.ted_hor_ini.setObjectName(_fromUtf8("ted_hor_ini"))
        self.gridLayout_2.addWidget(self.ted_hor_ini, 0, 1, 1, 1)
        self.cbx_estado = QtGui.QCheckBox(self.pag_exe)
        self.cbx_estado.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbx_estado.setChecked(True)
        self.cbx_estado.setObjectName(_fromUtf8("cbx_estado"))
        self.gridLayout_2.addWidget(self.cbx_estado, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 1, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/execute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_exe.addTab(self.pag_exe, icon, _fromUtf8(""))
        self.pag_anv = QtGui.QWidget()
        self.pag_anv.setObjectName(_fromUtf8("pag_anv"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pag_anv)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gbx_anv = QtGui.QGroupBox(self.pag_anv)
        self.gbx_anv.setObjectName(_fromUtf8("gbx_anv"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbx_anv)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.qtw_anv = QtGui.QTableWidget(self.gbx_anv)
        self.qtw_anv.setObjectName(_fromUtf8("qtw_anv"))
        self.qtw_anv.setColumnCount(0)
        self.qtw_anv.setRowCount(0)
        self.verticalLayout_3.addWidget(self.qtw_anv)
        self.verticalLayout_5.addWidget(self.gbx_anv)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_exe.addTab(self.pag_anv, icon1, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_exe)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.frm_dbb = QtGui.QFrame(self.wid_data)
        self.frm_dbb.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_dbb.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_dbb.setObjectName(_fromUtf8("frm_dbb"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frm_dbb)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_new = QtGui.QPushButton(self.frm_dbb)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new.setIcon(icon2)
        self.btn_new.setObjectName(_fromUtf8("btn_new"))
        self.horizontalLayout_3.addWidget(self.btn_new)
        self.btn_del = QtGui.QPushButton(self.frm_dbb)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del.setIcon(icon3)
        self.btn_del.setObjectName(_fromUtf8("btn_del"))
        self.horizontalLayout_3.addWidget(self.btn_del)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.dbb_exe = QtGui.QDialogButtonBox(self.frm_dbb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbb_exe.sizePolicy().hasHeightForWidth())
        self.dbb_exe.setSizePolicy(sizePolicy)
        self.dbb_exe.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.dbb_exe.setObjectName(_fromUtf8("dbb_exe"))
        self.horizontalLayout_3.addWidget(self.dbb_exe)
        self.verticalLayout.addWidget(self.frm_dbb)
        self.horizontalLayout_2.addWidget(self.splitter)

        self.retranslateUi(CDlgExeDataNEW)
        self.tab_exe.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CDlgExeDataNEW)

    def retranslateUi(self, CDlgExeDataNEW):
        CDlgExeDataNEW.setWindowTitle(_translate("CDlgExeDataNEW", "Edição de Exercícios", None))
        self.lbl_desc.setText(_translate("CDlgExeDataNEW", "Descrição:", None))
        self.txt_indc.setText(_translate("CDlgExeDataNEW", "TEST001", None))
        self.lbl_indc.setText(_translate("CDlgExeDataNEW", "Indicativo:", None))
        self.lbl_vel_exe.setText(_translate("CDlgExeDataNEW", "Velocidade:", None))
        self.lbl_hor_ini.setText(_translate("CDlgExeDataNEW", "Hora inicial:", None))
        self.ted_hor_ini.setDisplayFormat(_translate("CDlgExeDataNEW", "h:mm", None))
        self.cbx_estado.setText(_translate("CDlgExeDataNEW", "Congelado", None))
        self.tab_exe.setTabText(self.tab_exe.indexOf(self.pag_exe), _translate("CDlgExeDataNEW", "Exercício", None))
        self.gbx_anv.setTitle(_translate("CDlgExeDataNEW", "Tráfegos", None))
        self.qtw_anv.setSortingEnabled(True)
        self.tab_exe.setTabText(self.tab_exe.indexOf(self.pag_anv), _translate("CDlgExeDataNEW", "Tráfegos", None))
        self.btn_new.setText(_translate("CDlgExeDataNEW", "Novo", None))
        self.btn_del.setText(_translate("CDlgExeDataNEW", "Remove", None))

import resources_rc
