# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_exe_edit_new.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgExeEditNEW(object):
    def setupUi(self, CDlgExeEditNEW):
        CDlgExeEditNEW.setObjectName(_fromUtf8("CDlgExeEditNEW"))
        CDlgExeEditNEW.resize(616, 171)
        CDlgExeEditNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgExeEditNEW.setSizeGripEnabled(True)
        CDlgExeEditNEW.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(CDlgExeEditNEW)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frmID = QtGui.QFrame(CDlgExeEditNEW)
        self.frmID.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmID.setFrameShadow(QtGui.QFrame.Raised)
        self.frmID.setLineWidth(1)
        self.frmID.setObjectName(_fromUtf8("frmID"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmID)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblNome = QtGui.QLabel(self.frmID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNome.sizePolicy().hasHeightForWidth())
        self.lblNome.setSizePolicy(sizePolicy)
        self.lblNome.setObjectName(_fromUtf8("lblNome"))
        self.horizontalLayout.addWidget(self.lblNome)
        self.qleInd = QtGui.QLineEdit(self.frmID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleInd.sizePolicy().hasHeightForWidth())
        self.qleInd.setSizePolicy(sizePolicy)
        self.qleInd.setObjectName(_fromUtf8("qleInd"))
        self.horizontalLayout.addWidget(self.qleInd)
        self.lblDesc = QtGui.QLabel(self.frmID)
        self.lblDesc.setObjectName(_fromUtf8("lblDesc"))
        self.horizontalLayout.addWidget(self.lblDesc)
        self.qleDsc = QtGui.QLineEdit(self.frmID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleDsc.sizePolicy().hasHeightForWidth())
        self.qleDsc.setSizePolicy(sizePolicy)
        self.qleDsc.setObjectName(_fromUtf8("qleDsc"))
        self.horizontalLayout.addWidget(self.qleDsc)
        self.verticalLayout.addWidget(self.frmID)
        self.frmGrl = QtGui.QFrame(CDlgExeEditNEW)
        self.frmGrl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGrl.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGrl.setObjectName(_fromUtf8("frmGrl"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmGrl)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widGrl1 = QtGui.QWidget(self.frmGrl)
        self.widGrl1.setObjectName(_fromUtf8("widGrl1"))
        self.gridLayout_8 = QtGui.QGridLayout(self.widGrl1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.widGrlIni = QtGui.QWidget(self.widGrl1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widGrlIni.sizePolicy().hasHeightForWidth())
        self.widGrlIni.setSizePolicy(sizePolicy)
        self.widGrlIni.setObjectName(_fromUtf8("widGrlIni"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widGrlIni)
        self.horizontalLayout_5.setMargin(1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.qsbGrlIniHor = QtGui.QSpinBox(self.widGrlIni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbGrlIniHor.sizePolicy().hasHeightForWidth())
        self.qsbGrlIniHor.setSizePolicy(sizePolicy)
        self.qsbGrlIniHor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbGrlIniHor.setMaximum(23)
        self.qsbGrlIniHor.setObjectName(_fromUtf8("qsbGrlIniHor"))
        self.horizontalLayout_5.addWidget(self.qsbGrlIniHor)
        self.qsbGrlIniMin = QtGui.QSpinBox(self.widGrlIni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbGrlIniMin.sizePolicy().hasHeightForWidth())
        self.qsbGrlIniMin.setSizePolicy(sizePolicy)
        self.qsbGrlIniMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbGrlIniMin.setMaximum(59)
        self.qsbGrlIniMin.setSingleStep(5)
        self.qsbGrlIniMin.setObjectName(_fromUtf8("qsbGrlIniMin"))
        self.horizontalLayout_5.addWidget(self.qsbGrlIniMin)
        self.gridLayout_8.addWidget(self.widGrlIni, 1, 1, 1, 1)
        self.lblGrlIni = QtGui.QLabel(self.widGrl1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGrlIni.sizePolicy().hasHeightForWidth())
        self.lblGrlIni.setSizePolicy(sizePolicy)
        self.lblGrlIni.setObjectName(_fromUtf8("lblGrlIni"))
        self.gridLayout_8.addWidget(self.lblGrlIni, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 1, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.widGrl1)
        self.verticalLayout.addWidget(self.frmGrl)
        self.bbxExeEdit = QtGui.QWidget(CDlgExeEditNEW)
        self.bbxExeEdit.setObjectName(_fromUtf8("bbxExeEdit"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.bbxExeEdit)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnCancel = QtGui.QPushButton(self.bbxExeEdit)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_6.addWidget(self.btnCancel)
        self.btnOk = QtGui.QPushButton(self.bbxExeEdit)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/editedit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon1)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout_6.addWidget(self.btnOk)
        self.verticalLayout.addWidget(self.bbxExeEdit)
        self.lblNome.setBuddy(self.qleInd)
        self.lblDesc.setBuddy(self.qleDsc)
        self.lblGrlIni.setBuddy(self.widGrlIni)

        self.retranslateUi(CDlgExeEditNEW)
        QtCore.QMetaObject.connectSlotsByName(CDlgExeEditNEW)

    def retranslateUi(self, CDlgExeEditNEW):
        CDlgExeEditNEW.setWindowTitle(_translate("CDlgExeEditNEW", "Edição de Exercícios", None))
        self.lblNome.setText(_translate("CDlgExeEditNEW", "&Sigla:", None))
        self.lblDesc.setText(_translate("CDlgExeEditNEW", "Descrição:", None))
        self.lblGrlIni.setText(_translate("CDlgExeEditNEW", "Hora inicial:", None))
        self.btnCancel.setText(_translate("CDlgExeEditNEW", "Cancela", None))
        self.btnOk.setText(_translate("CDlgExeEditNEW", "Ok", None))

import resources_rc
