# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_brk_trj_edit_new.ui'
#
# Created: Wed Jul  5 09:26:18 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgBrkTrjEditNEW(object):
    def setupUi(self, CDlgBrkTrjEditNEW):
        CDlgBrkTrjEditNEW.setObjectName(_fromUtf8("CDlgBrkTrjEditNEW"))
        CDlgBrkTrjEditNEW.resize(464, 375)
        CDlgBrkTrjEditNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgBrkTrjEditNEW.setSizeGripEnabled(True)
        CDlgBrkTrjEditNEW.setModal(True)
        self.verticalLayout_3 = QtGui.QVBoxLayout(CDlgBrkTrjEditNEW)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frmPtoTrj = QtGui.QFrame(CDlgBrkTrjEditNEW)
        self.frmPtoTrj.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmPtoTrj.setFrameShadow(QtGui.QFrame.Raised)
        self.frmPtoTrj.setObjectName(_fromUtf8("frmPtoTrj"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frmPtoTrj)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbxTrjPts = QtGui.QGroupBox(self.frmPtoTrj)
        self.gbxTrjPts.setObjectName(_fromUtf8("gbxTrjPts"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbxTrjPts)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbxTrjPos = QtGui.QGroupBox(self.gbxTrjPts)
        self.gbxTrjPos.setObjectName(_fromUtf8("gbxTrjPos"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gbxTrjPos)
        self.gridLayout_6.setMargin(3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbxTCrd = QtGui.QComboBox(self.gbxTrjPos)
        self.cbxTCrd.setMinimumSize(QtCore.QSize(150, 0))
        self.cbxTCrd.setObjectName(_fromUtf8("cbxTCrd"))
        self.cbxTCrd.addItem(_fromUtf8(""))
        self.cbxTCrd.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbxTCrd, 0, 0, 1, 1)
        self.stkTCrd = QtGui.QStackedWidget(self.gbxTrjPos)
        self.stkTCrd.setObjectName(_fromUtf8("stkTCrd"))
        self.crdGeo = QtGui.QWidget()
        self.crdGeo.setObjectName(_fromUtf8("crdGeo"))
        self.gridLayout_9 = QtGui.QGridLayout(self.crdGeo)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.dsbGeoLng = QtGui.QDoubleSpinBox(self.crdGeo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbGeoLng.sizePolicy().hasHeightForWidth())
        self.dsbGeoLng.setSizePolicy(sizePolicy)
        self.dsbGeoLng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbGeoLng.setDecimals(4)
        self.dsbGeoLng.setMinimum(-180.0)
        self.dsbGeoLng.setMaximum(180.0)
        self.dsbGeoLng.setObjectName(_fromUtf8("dsbGeoLng"))
        self.gridLayout_9.addWidget(self.dsbGeoLng, 1, 1, 1, 1)
        self.lblGeoAlt = QtGui.QLabel(self.crdGeo)
        self.lblGeoAlt.setMinimumSize(QtCore.QSize(0, 0))
        self.lblGeoAlt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGeoAlt.setObjectName(_fromUtf8("lblGeoAlt"))
        self.gridLayout_9.addWidget(self.lblGeoAlt, 2, 0, 1, 1)
        self.dsbGeoLat = QtGui.QDoubleSpinBox(self.crdGeo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbGeoLat.sizePolicy().hasHeightForWidth())
        self.dsbGeoLat.setSizePolicy(sizePolicy)
        self.dsbGeoLat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dsbGeoLat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbGeoLat.setDecimals(4)
        self.dsbGeoLat.setMinimum(-90.0)
        self.dsbGeoLat.setMaximum(90.0)
        self.dsbGeoLat.setObjectName(_fromUtf8("dsbGeoLat"))
        self.gridLayout_9.addWidget(self.dsbGeoLat, 0, 1, 1, 1)
        self.lblGeoLng = QtGui.QLabel(self.crdGeo)
        self.lblGeoLng.setMinimumSize(QtCore.QSize(0, 0))
        self.lblGeoLng.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGeoLng.setObjectName(_fromUtf8("lblGeoLng"))
        self.gridLayout_9.addWidget(self.lblGeoLng, 1, 0, 1, 1)
        self.dsbGeoAlt = QtGui.QDoubleSpinBox(self.crdGeo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbGeoAlt.sizePolicy().hasHeightForWidth())
        self.dsbGeoAlt.setSizePolicy(sizePolicy)
        self.dsbGeoAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbGeoAlt.setDecimals(1)
        self.dsbGeoAlt.setMaximum(99900.0)
        self.dsbGeoAlt.setSingleStep(10.0)
        self.dsbGeoAlt.setObjectName(_fromUtf8("dsbGeoAlt"))
        self.gridLayout_9.addWidget(self.dsbGeoAlt, 2, 1, 1, 1)
        self.lblGeoLat = QtGui.QLabel(self.crdGeo)
        self.lblGeoLat.setObjectName(_fromUtf8("lblGeoLat"))
        self.gridLayout_9.addWidget(self.lblGeoLat, 0, 0, 1, 1)
        self.stkTCrd.addWidget(self.crdGeo)
        self.crdPFix = QtGui.QWidget()
        self.crdPFix.setObjectName(_fromUtf8("crdPFix"))
        self.gridLayout_8 = QtGui.QGridLayout(self.crdPFix)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblFixoLat = QtGui.QLabel(self.crdPFix)
        self.lblFixoLat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFixoLat.setObjectName(_fromUtf8("lblFixoLat"))
        self.gridLayout_8.addWidget(self.lblFixoLat, 1, 0, 1, 1)
        self.lblFixoLng = QtGui.QLabel(self.crdPFix)
        self.lblFixoLng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFixoLng.setObjectName(_fromUtf8("lblFixoLng"))
        self.gridLayout_8.addWidget(self.lblFixoLng, 2, 0, 1, 1)
        self.qleFixoLat = QtGui.QLineEdit(self.crdPFix)
        self.qleFixoLat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleFixoLat.setReadOnly(True)
        self.qleFixoLat.setObjectName(_fromUtf8("qleFixoLat"))
        self.gridLayout_8.addWidget(self.qleFixoLat, 1, 1, 1, 1)
        self.qleFixoLng = QtGui.QLineEdit(self.crdPFix)
        self.qleFixoLng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleFixoLng.setReadOnly(True)
        self.qleFixoLng.setObjectName(_fromUtf8("qleFixoLng"))
        self.gridLayout_8.addWidget(self.qleFixoLng, 2, 1, 1, 1)
        self.cbxFixo = QtGui.QComboBox(self.crdPFix)
        self.cbxFixo.setObjectName(_fromUtf8("cbxFixo"))
        self.gridLayout_8.addWidget(self.cbxFixo, 0, 1, 1, 1)
        self.lblFixo = QtGui.QLabel(self.crdPFix)
        self.lblFixo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFixo.setObjectName(_fromUtf8("lblFixo"))
        self.gridLayout_8.addWidget(self.lblFixo, 0, 0, 1, 1)
        self.stkTCrd.addWidget(self.crdPFix)
        self.gridLayout_6.addWidget(self.stkTCrd, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbxTrjPos)
        self.widPtoTrjData = QtGui.QWidget(self.gbxTrjPts)
        self.widPtoTrjData.setObjectName(_fromUtf8("widPtoTrjData"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widPtoTrjData)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbxTrjAlt = QtGui.QGroupBox(self.widPtoTrjData)
        self.gbxTrjAlt.setObjectName(_fromUtf8("gbxTrjAlt"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.gbxTrjAlt)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.dsbTrjAlt = QtGui.QDoubleSpinBox(self.gbxTrjAlt)
        self.dsbTrjAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbTrjAlt.setDecimals(1)
        self.dsbTrjAlt.setMaximum(99900.0)
        self.dsbTrjAlt.setSingleStep(50.0)
        self.dsbTrjAlt.setObjectName(_fromUtf8("dsbTrjAlt"))
        self.horizontalLayout_8.addWidget(self.dsbTrjAlt)
        self.horizontalLayout.addWidget(self.gbxTrjAlt)
        self.gbxTrjVel = QtGui.QGroupBox(self.widPtoTrjData)
        self.gbxTrjVel.setObjectName(_fromUtf8("gbxTrjVel"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbxTrjVel)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dsbTrjVel = QtGui.QDoubleSpinBox(self.gbxTrjVel)
        self.dsbTrjVel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbTrjVel.setDecimals(1)
        self.dsbTrjVel.setMaximum(1000.0)
        self.dsbTrjVel.setSingleStep(10.0)
        self.dsbTrjVel.setObjectName(_fromUtf8("dsbTrjVel"))
        self.horizontalLayout_2.addWidget(self.dsbTrjVel)
        self.horizontalLayout.addWidget(self.gbxTrjVel)
        self.gbxTrjProc = QtGui.QGroupBox(self.widPtoTrjData)
        self.gbxTrjProc.setObjectName(_fromUtf8("gbxTrjProc"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.gbxTrjProc)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.cbxTrjPrc = QtGui.QComboBox(self.gbxTrjProc)
        self.cbxTrjPrc.setObjectName(_fromUtf8("cbxTrjPrc"))
        self.horizontalLayout_14.addWidget(self.cbxTrjPrc)
        self.horizontalLayout.addWidget(self.gbxTrjProc)
        self.verticalLayout.addWidget(self.widPtoTrjData)
        self.verticalLayout_2.addWidget(self.gbxTrjPts)
        self.verticalLayout_3.addWidget(self.frmPtoTrj)
        self.widget = QtGui.QWidget(CDlgBrkTrjEditNEW)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btnCancel = QtGui.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_6.addWidget(self.btnCancel)
        self.btnOk = QtGui.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon1)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout_6.addWidget(self.btnOk)
        self.verticalLayout_3.addWidget(self.widget)

        self.retranslateUi(CDlgBrkTrjEditNEW)
        self.stkTCrd.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CDlgBrkTrjEditNEW)
        CDlgBrkTrjEditNEW.setTabOrder(self.cbxTCrd, self.dsbGeoLat)
        CDlgBrkTrjEditNEW.setTabOrder(self.dsbGeoLat, self.dsbGeoLng)
        CDlgBrkTrjEditNEW.setTabOrder(self.dsbGeoLng, self.dsbGeoAlt)
        CDlgBrkTrjEditNEW.setTabOrder(self.dsbGeoAlt, self.cbxFixo)
        CDlgBrkTrjEditNEW.setTabOrder(self.cbxFixo, self.qleFixoLat)
        CDlgBrkTrjEditNEW.setTabOrder(self.qleFixoLat, self.qleFixoLng)
        CDlgBrkTrjEditNEW.setTabOrder(self.qleFixoLng, self.dsbTrjAlt)
        CDlgBrkTrjEditNEW.setTabOrder(self.dsbTrjAlt, self.dsbTrjVel)
        CDlgBrkTrjEditNEW.setTabOrder(self.dsbTrjVel, self.cbxTrjPrc)
        CDlgBrkTrjEditNEW.setTabOrder(self.cbxTrjPrc, self.btnCancel)
        CDlgBrkTrjEditNEW.setTabOrder(self.btnCancel, self.btnOk)

    def retranslateUi(self, CDlgBrkTrjEditNEW):
        CDlgBrkTrjEditNEW.setWindowTitle(_translate("CDlgBrkTrjEditNEW", "Edição de Trajetórias", None))
        self.gbxTrjPts.setTitle(_translate("CDlgBrkTrjEditNEW", "Ponto da Trajetória", None))
        self.gbxTrjPos.setTitle(_translate("CDlgBrkTrjEditNEW", "Posicão", None))
        self.cbxTCrd.setItemText(0, _translate("CDlgBrkTrjEditNEW", "G - Geográfica", None))
        self.cbxTCrd.setItemText(1, _translate("CDlgBrkTrjEditNEW", "F - Fixo", None))
        self.lblGeoAlt.setText(_translate("CDlgBrkTrjEditNEW", "Altitude (ft):", None))
        self.lblGeoLng.setText(_translate("CDlgBrkTrjEditNEW", "Longitude:", None))
        self.lblGeoLat.setText(_translate("CDlgBrkTrjEditNEW", "Latitude:", None))
        self.lblFixoLat.setText(_translate("CDlgBrkTrjEditNEW", "Latitude:", None))
        self.lblFixoLng.setText(_translate("CDlgBrkTrjEditNEW", "Longitude:", None))
        self.lblFixo.setText(_translate("CDlgBrkTrjEditNEW", "Fixo:", None))
        self.gbxTrjAlt.setTitle(_translate("CDlgBrkTrjEditNEW", "Altitude (ft)", None))
        self.gbxTrjVel.setTitle(_translate("CDlgBrkTrjEditNEW", "Velocidade (kt)", None))
        self.gbxTrjProc.setTitle(_translate("CDlgBrkTrjEditNEW", "Procedimento", None))
        self.btnCancel.setText(_translate("CDlgBrkTrjEditNEW", "Cancela", None))
        self.btnOk.setText(_translate("CDlgBrkTrjEditNEW", "Ok", None))

import resources_rc
