# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_trj_data_new.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgTrjDataNEW(object):
    def setupUi(self, CDlgTrjDataNEW):
        CDlgTrjDataNEW.setObjectName(_fromUtf8("CDlgTrjDataNEW"))
        CDlgTrjDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        CDlgTrjDataNEW.resize(863, 759)
        CDlgTrjDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgTrjDataNEW.setSizeGripEnabled(True)
        CDlgTrjDataNEW.setModal(True)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(CDlgTrjDataNEW)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter_2 = QtGui.QSplitter(CDlgTrjDataNEW)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widPrcTab = QtGui.QWidget(self.splitter_2)
        self.widPrcTab.setObjectName(_fromUtf8("widPrcTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widPrcTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.qtwTrjTab = QtGui.QTableWidget(self.widPrcTab)
        self.qtwTrjTab.setObjectName(_fromUtf8("qtwTrjTab"))
        self.qtwTrjTab.setColumnCount(0)
        self.qtwTrjTab.setRowCount(0)
        self.verticalLayout_4.addWidget(self.qtwTrjTab)
        self.frame = QtGui.QFrame(self.widPrcTab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnTrjNew = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTrjNew.setIcon(icon)
        self.btnTrjNew.setObjectName(_fromUtf8("btnTrjNew"))
        self.horizontalLayout_5.addWidget(self.btnTrjNew)
        self.btnTrjEdit = QtGui.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTrjEdit.setIcon(icon1)
        self.btnTrjEdit.setObjectName(_fromUtf8("btnTrjEdit"))
        self.horizontalLayout_5.addWidget(self.btnTrjEdit)
        self.btnTrjDel = QtGui.QPushButton(self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTrjDel.setIcon(icon2)
        self.btnTrjDel.setObjectName(_fromUtf8("btnTrjDel"))
        self.horizontalLayout_5.addWidget(self.btnTrjDel)
        self.verticalLayout_4.addWidget(self.frame)
        self.widPrcDat = QtGui.QWidget(self.splitter_2)
        self.widPrcDat.setObjectName(_fromUtf8("widPrcDat"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widPrcDat)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frmPrcID = QtGui.QFrame(self.widPrcDat)
        self.frmPrcID.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmPrcID.setFrameShadow(QtGui.QFrame.Raised)
        self.frmPrcID.setObjectName(_fromUtf8("frmPrcID"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frmPrcID)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.qlePrcDesc = QtGui.QLineEdit(self.frmPrcID)
        self.qlePrcDesc.setReadOnly(True)
        self.qlePrcDesc.setObjectName(_fromUtf8("qlePrcDesc"))
        self.gridLayout_2.addWidget(self.qlePrcDesc, 2, 1, 1, 1)
        self.lblPrcDesc = QtGui.QLabel(self.frmPrcID)
        self.lblPrcDesc.setObjectName(_fromUtf8("lblPrcDesc"))
        self.gridLayout_2.addWidget(self.lblPrcDesc, 2, 0, 1, 1)
        self.lblPrcID = QtGui.QLabel(self.frmPrcID)
        self.lblPrcID.setObjectName(_fromUtf8("lblPrcID"))
        self.gridLayout_2.addWidget(self.lblPrcID, 1, 0, 1, 1)
        self.txtPrcID = QtGui.QLabel(self.frmPrcID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtPrcID.setFont(font)
        self.txtPrcID.setObjectName(_fromUtf8("txtPrcID"))
        self.gridLayout_2.addWidget(self.txtPrcID, 1, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.frmPrcID)
        self.frmPtoTrj = QtGui.QFrame(self.widPrcDat)
        self.frmPtoTrj.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmPtoTrj.setFrameShadow(QtGui.QFrame.Raised)
        self.frmPtoTrj.setObjectName(_fromUtf8("frmPtoTrj"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frmPtoTrj)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbxTrjPts = QtGui.QGroupBox(self.frmPtoTrj)
        self.gbxTrjPts.setObjectName(_fromUtf8("gbxTrjPts"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbxTrjPts)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qtwTabPtoTrj = QtGui.QTableWidget(self.gbxTrjPts)
        self.qtwTabPtoTrj.setObjectName(_fromUtf8("qtwTabPtoTrj"))
        self.qtwTabPtoTrj.setColumnCount(0)
        self.qtwTabPtoTrj.setRowCount(0)
        self.verticalLayout.addWidget(self.qtwTabPtoTrj)
        self.widBtnPtoTrj = QtGui.QWidget(self.gbxTrjPts)
        self.widBtnPtoTrj.setObjectName(_fromUtf8("widBtnPtoTrj"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widBtnPtoTrj)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btnPtoTrjNew = QtGui.QPushButton(self.widBtnPtoTrj)
        self.btnPtoTrjNew.setIcon(icon)
        self.btnPtoTrjNew.setObjectName(_fromUtf8("btnPtoTrjNew"))
        self.horizontalLayout_6.addWidget(self.btnPtoTrjNew)
        self.btnPtoTrjEdit = QtGui.QPushButton(self.widBtnPtoTrj)
        self.btnPtoTrjEdit.setIcon(icon1)
        self.btnPtoTrjEdit.setObjectName(_fromUtf8("btnPtoTrjEdit"))
        self.horizontalLayout_6.addWidget(self.btnPtoTrjEdit)
        self.btnPtoTrjDel = QtGui.QPushButton(self.widBtnPtoTrj)
        self.btnPtoTrjDel.setIcon(icon2)
        self.btnPtoTrjDel.setObjectName(_fromUtf8("btnPtoTrjDel"))
        self.horizontalLayout_6.addWidget(self.btnPtoTrjDel)
        self.verticalLayout.addWidget(self.widBtnPtoTrj)
        self.verticalLayout_2.addWidget(self.gbxTrjPts)
        self.verticalLayout_8.addWidget(self.frmPtoTrj)
        self.frmPrcBBX = QtGui.QFrame(self.widPrcDat)
        self.frmPrcBBX.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmPrcBBX.setFrameShadow(QtGui.QFrame.Raised)
        self.frmPrcBBX.setObjectName(_fromUtf8("frmPrcBBX"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmPrcBBX)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bbxTrjTab = QtGui.QDialogButtonBox(self.frmPrcBBX)
        self.bbxTrjTab.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bbxTrjTab.setObjectName(_fromUtf8("bbxTrjTab"))
        self.horizontalLayout_3.addWidget(self.bbxTrjTab)
        self.verticalLayout_8.addWidget(self.frmPrcBBX)
        self.horizontalLayout_4.addWidget(self.splitter_2)

        self.retranslateUi(CDlgTrjDataNEW)
        QtCore.QMetaObject.connectSlotsByName(CDlgTrjDataNEW)
        CDlgTrjDataNEW.setTabOrder(self.qtwTrjTab, self.qtwTabPtoTrj)
        CDlgTrjDataNEW.setTabOrder(self.qtwTabPtoTrj, self.btnPtoTrjNew)
        CDlgTrjDataNEW.setTabOrder(self.btnPtoTrjNew, self.btnPtoTrjDel)

    def retranslateUi(self, CDlgTrjDataNEW):
        CDlgTrjDataNEW.setWindowTitle(_translate("CDlgTrjDataNEW", "Edição de trajetórias", None))
        self.btnTrjNew.setText(_translate("CDlgTrjDataNEW", "Novo", None))
        self.btnTrjEdit.setText(_translate("CDlgTrjDataNEW", "Edita", None))
        self.btnTrjDel.setText(_translate("CDlgTrjDataNEW", "Remove", None))
        self.lblPrcDesc.setText(_translate("CDlgTrjDataNEW", "Descrição:", None))
        self.lblPrcID.setText(_translate("CDlgTrjDataNEW", "Indicativo:", None))
        self.txtPrcID.setText(_translate("CDlgTrjDataNEW", "PRC001", None))
        self.gbxTrjPts.setTitle(_translate("CDlgTrjDataNEW", "Pontos da Trajetória", None))
        self.btnPtoTrjNew.setText(_translate("CDlgTrjDataNEW", "Novo", None))
        self.btnPtoTrjEdit.setText(_translate("CDlgTrjDataNEW", "Edita", None))
        self.btnPtoTrjDel.setText(_translate("CDlgTrjDataNEW", "Remove", None))

import resources_rc
